In [1]:
import pandas as pd
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
import numpy as np
import csv 
import re
import string

In [2]:
University_data = pd.read_csv(
    "Final_data.csv" )

University_data

,Unnamed: 0.1,Unnamed: 0,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct,Keys
0,0,0,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Diploma,English,5.5,Academic Requirements You required current emp...,Introduction Asset Maintenance Management Asse...,Adelaide,"Australia,CQUniversity Australia,good Universi..."
1,1,1,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Certificate,English,6.0,Academic Requirements You required current emp...,Introduction Asset Maintenance Management Asse...,Adelaide,"Australia,CQUniversity Australia,good Universi..."
2,2,2,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,Academic Requirements For entry Graduate Diplo...,Effective Business Communications Statistics M...,Melbourne Brisbane Mackay Sydney,"Australia,CQUniversity Australia,good Universi..."
3,3,3,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,Academic Requirements For entry Graduate Certi...,Effective Business Communications Statistics M...,Melbourne Brisbane Mackay Sydney,"Australia,CQUniversity Australia,good Universi..."
4,4,4,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,Academic Requirements Entry requirementsSucces...,Safety Accident Phenomenology Human Factors Co...,Melbourne Brisbane Sydney,"Australia,CQUniversity Australia,good Universi..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33812,33812,33812,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,Academic Requirements Application Requirements...,Advanced Professional Communication Communicat...,Worcester United States,"United States,Clark University,good University..."
33813,33813,33813,United States,Clark University,301.0,Community Development Planning,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,People Places Theories Community Development P...,Worcester United States,"United States,Clark University,good University..."
33814,33814,33814,United States,Clark University,301.0,Teaching,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,Ways Knowing Physical Natural Sciences Element...,Worcester United States,"United States,Clark University,good University..."
33815,33815,33815,United States,Clark University,301.0,English,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,Pedagogy I Pedagogy II Pedagogy III Pedagogy I...,Worcester United States,"United States,Clark University,good University..."
33816,33816,33816,United States,Clark University,301.0,Community Global Health,MHS,English,6.5,Academic Requirements Create account our\xc2\x...,Social determinants health health inequities G...,Worcester United States,"United States,Clark University,good University..."

# Select the Features
Here we delete the features that we dont need them in our task . However we have to attentin that it strongly depends on the wssence of the problem.maybe the features that we elimenate here be vital in another task.
Here we select "country name" , "university name" , "university rank" , "program name" , "program type" , "structure" , "city" and "academic req"

In [3]:
University_data.drop( University_data.columns[[ 1 , 6 , 7 ,9 , 10 ,11 , 12 , 13 , 14 , 15 ,16 , 22 ]] , axis = 1  ,  inplace=True)

# Lower case
First we convert the text data to lower case. One of its benefit is that we can calculate the frequency of each word as simple as possible.

In [4]:

def remove_html(Series):
    for item in range(Series.size):
        text = str(Series[item])
        html_pattern = re.compile('<.*?>')
        Series.replace(Series[item] , html_pattern.sub(r'', text), inplace = True)
    print(Series)
remove_html(University_data["academic_req"])

0         Academic Requirements   Application Requireme...
1         Academic Requirements  Admission Requirements...
2         Academic Requirements   Application Requireme...
3         Academic Requirements  CIS Application Requir...
4         Academic Requirements   IESM Application Requ...
                               ...
60420     Academic Requirements  a) a recognized 3-year...
60421     Academic Requirements  To gain entry into thi...
60422     Academic Requirements  This Graduate Certific...
60423     Academic Requirements  a) a recognized 3-year...
60424     Academic Requirements  Candidates should poss...
Name: academic_req, Length: 60425, dtype: object

# Removal of Punctuations
One another common text preprocessing technique is to remove the punctuations from the text data.for example "[this is home !!] " is better to be "this is home "

In [21]:
# First we have to fill the NAN value in thease 2 series
University_data["structure"].fillna("no value", inplace =True)
University_data["city"].fillna("no value" , inplace = True)

In [23]:
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

University_data["structure_wo_punct"] = University_data["structure"].apply(lambda text: remove_punctuation(text))
University_data["city_wo_punct"] = University_data["city"].apply(lambda text: remove_punctuation(text))

In [25]:
# now we have to remove "city" and "structure" columns
University_data.drop( University_data.columns[[ 0 , 8 , 10 ,11 ]] , axis = 1  ,  inplace=True)
University_data

,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,Armenia,American University of Armenia,NaN,Economics,MSc,English,6.5,Academic Requirements Application Requireme...,Quantitative Methods for Economists Mathematic...,Yerevan
1,Armenia,American University of Armenia,NaN,Political Science and International Affairs,Master,English,6.5,Academic Requirements Admission Requirements...,no value,Yerevan
2,Armenia,American University of Armenia,NaN,Business Administration,MBA,English,6.5,Academic Requirements Application Requireme...,Managers with practical knowledge of accountin...,Yerevan
3,Armenia,American University of Armenia,NaN,Computer and Information Science,MSc,English,6.5,Academic Requirements CIS Application Requir...,Introduction to ObjectOriented Programming Dis...,Yerevan
4,Armenia,American University of Armenia,NaN,Industrial Engineering and Systems Management,MEng,English,6.5,Academic Requirements IESM Application Requ...,Probability Theory Analysis and Design of Data...,Yerevan
...,...,...,...,...,...,...,...,...,...,...
60420,Viet Nam,Engineering Institute of Technology,NaN,Electrical Systems,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Power Generation Underground Power System Desi...,no value
60421,Viet Nam,Engineering Institute of Technology,NaN,Industrial Automation,MEng,English,6.5,Academic Requirements To gain entry into thi...,Power Engineering Programmable Logic Controlle...,Perth
60422,Viet Nam,Engineering Institute of Technology,NaN,Renewable Energy Technologies,Postgraduate Certificate,English,NaN,Academic Requirements This Graduate Certific...,Unit 1 Fundamentals and General DistributionI...,no value
60423,Viet Nam,Engineering Institute of Technology,NaN,Safety,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Introduction to Safety Engineering and Risk Ma...,no value
60424,Viet Nam,Vietnam National University of Agriculture,NaN,Food Technology,MFT,English,NaN,Academic Requirements Candidates should poss...,no value,Hanoi

# Text Cleaning
Here we have to feel in the Nan elements. As we see we have lots of Nan value "ielts_score" serie so must design a policy for this column. we use the avarage of the ielts_scores of the same university for Nan fields.

In [41]:

for item in range(University_data["ielts_score"].size) : 
    if pd.isna(University_data["ielts_score"][item]) :
        
        avarage_score_of_the_same_university =University_data.loc[University_data["university_name"] == University_data["university_name"][item] , "ielts_score"].mean()
        University_data["ielts_score"].iloc[ item] = avarage_score_of_the_same_university 
        
University_data

/tmp/ipykernel_17328/2161528814.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  University_data["ielts_score"].iloc[ item] = avarage_score_of_the_same_university

,Unnamed: 0,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,0,Armenia,American University of Armenia,NaN,Economics,MSc,English,6.5,Academic Requirements Application Requireme...,Quantitative Methods for Economists Mathematic...,Yerevan
1,1,Armenia,American University of Armenia,NaN,Political Science and International Affairs,Master,English,6.5,Academic Requirements Admission Requirements...,no value,Yerevan
2,2,Armenia,American University of Armenia,NaN,Business Administration,MBA,English,6.5,Academic Requirements Application Requireme...,Managers with practical knowledge of accountin...,Yerevan
3,3,Armenia,American University of Armenia,NaN,Computer and Information Science,MSc,English,6.5,Academic Requirements CIS Application Requir...,Introduction to ObjectOriented Programming Dis...,Yerevan
4,4,Armenia,American University of Armenia,NaN,Industrial Engineering and Systems Management,MEng,English,6.5,Academic Requirements IESM Application Requ...,Probability Theory Analysis and Design of Data...,Yerevan
...,...,...,...,...,...,...,...,...,...,...,...
60420,60420,Viet Nam,Engineering Institute of Technology,NaN,Electrical Systems,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Power Generation Underground Power System Desi...,no value
60421,60421,Viet Nam,Engineering Institute of Technology,NaN,Industrial Automation,MEng,English,6.5,Academic Requirements To gain entry into thi...,Power Engineering Programmable Logic Controlle...,Perth
60422,60422,Viet Nam,Engineering Institute of Technology,NaN,Renewable Energy Technologies,Postgraduate Certificate,English,6.5,Academic Requirements This Graduate Certific...,Unit 1 Fundamentals and General DistributionI...,no value
60423,60423,Viet Nam,Engineering Institute of Technology,NaN,Safety,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Introduction to Safety Engineering and Risk Ma...,no value
60424,60424,Viet Nam,Vietnam National University of Agriculture,NaN,Food Technology,MFT,English,NaN,Academic Requirements Candidates should poss...,no value,Hanoi

In [18]:
# here we are going to remove the remained data with Non "ielts_score" field.
size_of_dataFrame = University_data["ielts_score"].size
for item in range(size_of_dataFrame) : 
    if pd.isna(University_data["ielts_score"][item]) :
        University_data.drop(item , inplace=True)
University_data

,Unnamed: 0.1,Unnamed: 0,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,0,0,Armenia,American University of Armenia,NaN,Economics,MSc,English,6.5,Academic Requirements Application Requireme...,Quantitative Methods for Economists Mathematic...,Yerevan
1,1,1,Armenia,American University of Armenia,NaN,Political Science and International Affairs,Master,English,6.5,Academic Requirements Admission Requirements...,no value,Yerevan
2,2,2,Armenia,American University of Armenia,NaN,Business Administration,MBA,English,6.5,Academic Requirements Application Requireme...,Managers with practical knowledge of accountin...,Yerevan
3,3,3,Armenia,American University of Armenia,NaN,Computer and Information Science,MSc,English,6.5,Academic Requirements CIS Application Requir...,Introduction to ObjectOriented Programming Dis...,Yerevan
4,4,4,Armenia,American University of Armenia,NaN,Industrial Engineering and Systems Management,MEng,English,6.5,Academic Requirements IESM Application Requ...,Probability Theory Analysis and Design of Data...,Yerevan
...,...,...,...,...,...,...,...,...,...,...,...,...
60413,60413,60413,United States,Eastern Michigan University,NaN,Hotel and Restaurant Management,MSc,English,6.5,Academic Requirements You need the followin...,Advanced Topics in FoodService Management Adva...,Ypsilanti United States
60420,60420,60420,Viet Nam,Engineering Institute of Technology,NaN,Electrical Systems,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Power Generation Underground Power System Desi...,no value
60421,60421,60421,Viet Nam,Engineering Institute of Technology,NaN,Industrial Automation,MEng,English,6.5,Academic Requirements To gain entry into thi...,Power Engineering Programmable Logic Controlle...,Perth
60422,60422,60422,Viet Nam,Engineering Institute of Technology,NaN,Renewable Energy Technologies,Postgraduate Certificate,English,6.5,Academic Requirements This Graduate Certific...,Unit 1 Fundamentals and General DistributionI...,no value
60423,60423,60423,Viet Nam,Engineering Institute of Technology,NaN,Safety,MEng,English,6.5,Academic Requirements a) a recognized 3-year...,Introduction to Safety Engineering and Risk Ma...,no value

In [4]:
# here we remove the data with null "rank" feild 
size_of_dataFrame = University_data["university_rank"].size
for item in range(size_of_dataFrame) : 
    if pd.isna(University_data["university_rank"][item]) :
        University_data.drop(item , inplace=True)
University_data

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
7,9,9,9,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Diploma,English,5.5,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,no value
8,10,10,10,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Certificate,English,6.0,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,Adelaide
9,11,11,11,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
10,12,12,12,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
11,13,13,13,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,Academic Requirements Entry requirementsSucc...,Safety and Accident Phenomenology Human Factor...,no value
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55672,60213,60213,60213,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,Academic Requirements Application Requireme...,Advanced Professional Communication Communicat...,Worcester United States
55673,60214,60214,60214,United States,Clark University,301.0,Community Development and Planning,MA,English,6.5,Academic Requirements Clark Graduate School ...,People and Places Theories of Community Develo...,Worcester United States
55674,60215,60215,60215,United States,Clark University,301.0,Teaching,MA,English,6.5,Academic Requirements Clark Graduate School ...,Ways of Knowing in the Physical and Natural Sc...,Worcester United States
55675,60216,60216,60216,United States,Clark University,301.0,English,MA,English,6.5,Academic Requirements Clark Graduate School ...,Pedagogy I Pedagogy II Pedagogy III Pedagogy I...,Worcester United States
55676,60217,60217,60217,United States,Clark University,301.0,Community and Global Health,MHS,English,6.5,Academic Requirements Create an account on o...,Social determinants of health and health inequ...,Worcester United States

In [13]:
# # we have to reindex our data
University_data.reset_index(inplace=True )
University_data.drop( University_data.columns[[ 0 , 1, 2 ,3 ,4 ]] , axis = 1  ,  inplace=True)
University_data

,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Diploma,English,5.5,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,no value
1,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Certificate,English,6.0,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,Adelaide
2,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
3,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
4,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,Academic Requirements Entry requirementsSucc...,Safety and Accident Phenomenology Human Factor...,no value
...,...,...,...,...,...,...,...,...,...,...
33812,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,Academic Requirements Application Requireme...,Advanced Professional Communication Communicat...,Worcester United States
33813,United States,Clark University,301.0,Community Development and Planning,MA,English,6.5,Academic Requirements Clark Graduate School ...,People and Places Theories of Community Develo...,Worcester United States
33814,United States,Clark University,301.0,Teaching,MA,English,6.5,Academic Requirements Clark Graduate School ...,Ways of Knowing in the Physical and Natural Sc...,Worcester United States
33815,United States,Clark University,301.0,English,MA,English,6.5,Academic Requirements Clark Graduate School ...,Pedagogy I Pedagogy II Pedagogy III Pedagogy I...,Worcester United States
33816,United States,Clark University,301.0,Community and Global Health,MHS,English,6.5,Academic Requirements Create an account on o...,Social determinants of health and health inequ...,Worcester United States

In [15]:
#  we have to find the city of universities 
size_of_dataFrame = University_data["ielts_score"].size
for item in range(size_of_dataFrame) : 
    if University_data["city_wo_punct"][item] == 'no value' :
        University_data["city_wo_punct"].iloc[ item] = University_data["city_wo_punct"].iloc[ item + 1]

University_data

/tmp/ipykernel_6630/331693177.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  University_data["city_wo_punct"].iloc[ item] = University_data["city_wo_punct"].iloc[ item + 1]

,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Diploma,English,5.5,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,Adelaide
1,Australia,CQUniversity Australia,401.0,Asset and Maintenance Management,Postgraduate Certificate,English,6.0,Academic Requirements You are required to ha...,Introduction to Asset and Maintenance Manageme...,Adelaide
2,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
3,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,Academic Requirements For entry into the Gra...,Effective Business Communications Statistics f...,Melbourne Brisbane Mackay Sydney
4,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,Academic Requirements Entry requirementsSucc...,Safety and Accident Phenomenology Human Factor...,Melbourne Brisbane Sydney
...,...,...,...,...,...,...,...,...,...,...
33812,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,Academic Requirements Application Requireme...,Advanced Professional Communication Communicat...,Worcester United States
33813,United States,Clark University,301.0,Community Development and Planning,MA,English,6.5,Academic Requirements Clark Graduate School ...,People and Places Theories of Community Develo...,Worcester United States
33814,United States,Clark University,301.0,Teaching,MA,English,6.5,Academic Requirements Clark Graduate School ...,Ways of Knowing in the Physical and Natural Sc...,Worcester United States
33815,United States,Clark University,301.0,English,MA,English,6.5,Academic Requirements Clark Graduate School ...,Pedagogy I Pedagogy II Pedagogy III Pedagogy I...,Worcester United States
33816,United States,Clark University,301.0,Community and Global Health,MHS,English,6.5,Academic Requirements Create an account on o...,Social determinants of health and health inequ...,Worcester United States

# Remove stopwards
here we have to remove stopwards like "the" , "a" , etc . these words dont provide valuable information .

In [43]:
# if we want use nltk we have to download the data using :
# nltk.download('stopwords')
# the link below can guide us to download 
#  https://www.projectpro.io/recipes/download-nltk-library

In [41]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

In [44]:
#  we have to remove stopwards in "program_name" , "academic_req" , "structure_wo_punct" , "city_wo_punct"
University_data["program_name"] = University_data["program_name"].apply(lambda text: remove_stopwords(text))
University_data["academic_req"] = University_data["academic_req"].apply(lambda text: remove_stopwords(text))
University_data["structure_wo_punct"] = University_data["structure_wo_punct"].apply(lambda text: remove_stopwords(text))
University_data["city_wo_punct"] = University_data["city_wo_punct"].apply(lambda text: remove_stopwords(text))
University_data

,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Diploma,English,5.5,Academic Requirements You required current emp...,Introduction Asset Maintenance Management Asse...,Adelaide
1,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Certificate,English,6.0,Academic Requirements You required current emp...,Introduction Asset Maintenance Management Asse...,Adelaide
2,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,Academic Requirements For entry Graduate Diplo...,Effective Business Communications Statistics M...,Melbourne Brisbane Mackay Sydney
3,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,Academic Requirements For entry Graduate Certi...,Effective Business Communications Statistics M...,Melbourne Brisbane Mackay Sydney
4,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,Academic Requirements Entry requirementsSucces...,Safety Accident Phenomenology Human Factors Co...,Melbourne Brisbane Sydney
...,...,...,...,...,...,...,...,...,...,...
33812,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,Academic Requirements Application Requirements...,Advanced Professional Communication Communicat...,Worcester United States
33813,United States,Clark University,301.0,Community Development Planning,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,People Places Theories Community Development P...,Worcester United States
33814,United States,Clark University,301.0,Teaching,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,Ways Knowing Physical Natural Sciences Element...,Worcester United States
33815,United States,Clark University,301.0,English,MA,English,6.5,Academic Requirements Clark Graduate School Ap...,Pedagogy I Pedagogy II Pedagogy III Pedagogy I...,Worcester United States
33816,United States,Clark University,301.0,Community Global Health,MHS,English,6.5,Academic Requirements Create account our\xc2\x...,Social determinants health health inequities G...,Worcester United States

# Tokanization
We have to tokanize "academic_req" and "structure_wo_punct" .

In [24]:
size = len(University_data) 
for item in range(size) :
    if not pd.isna(University_data["academic_req" ].iloc[item  ]):
        University_data["academic_req" ].iloc[item  ] = University_data["academic_req" ].iloc[item  ].split()
    if not pd.isna(University_data["structure_wo_punct" ].iloc[item  ] ) :
        University_data["structure_wo_punct" ].iloc[item  ] = University_data["structure_wo_punct" ].iloc[item  ].split()

University_data

/tmp/ipykernel_4307/3659213286.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  University_data["academic_req" ].iloc[item  ] = University_data["academic_req" ].iloc[item  ].split()
/tmp/ipykernel_4307/3659213286.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  University_data["structure_wo_punct" ].iloc[item  ] = University_data["structure_wo_punct" ].iloc[item  ].split()

,Unnamed: 0,country_name,university_name,university_rank,program_name,program_type,language,ielts_score,academic_req,structure_wo_punct,city_wo_punct
0,0,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Diploma,English,5.5,"[Academic, Requirements, You, required, curren...","[Introduction, Asset, Maintenance, Management,...",Adelaide
1,1,Australia,CQUniversity Australia,401.0,Asset Maintenance Management,Postgraduate Certificate,English,6.0,"[Academic, Requirements, You, required, curren...","[Introduction, Asset, Maintenance, Management,...",Adelaide
2,2,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Diploma,English,6.0,"[Academic, Requirements, For, entry, Graduate,...","[Effective, Business, Communications, Statisti...",Melbourne Brisbane Mackay Sydney
3,3,Australia,CQUniversity Australia,401.0,Business Administration,Postgraduate Certificate,English,6.0,"[Academic, Requirements, For, entry, Graduate,...","[Effective, Business, Communications, Statisti...",Melbourne Brisbane Mackay Sydney
4,4,Australia,CQUniversity Australia,401.0,Fatigue Risk Management,Postgraduate Certificate,English,6.0,"[Academic, Requirements, Entry, requirementsSu...","[Safety, Accident, Phenomenology, Human, Facto...",Melbourne Brisbane Sydney
...,...,...,...,...,...,...,...,...,...,...,...
33812,33812,United States,Clark University,301.0,Professional Communication,MSc,English,6.5,"[Academic, Requirements, Application, Requirem...","[Advanced, Professional, Communication, Commun...",Worcester United States
33813,33813,United States,Clark University,301.0,Community Development Planning,MA,English,6.5,"[Academic, Requirements, Clark, Graduate, Scho...","[People, Places, Theories, Community, Developm...",Worcester United States
33814,33814,United States,Clark University,301.0,Teaching,MA,English,6.5,"[Academic, Requirements, Clark, Graduate, Scho...","[Ways, Knowing, Physical, Natural, Sciences, E...",Worcester United States
33815,33815,United States,Clark University,301.0,English,MA,English,6.5,"[Academic, Requirements, Clark, Graduate, Scho...","[Pedagogy, I, Pedagogy, II, Pedagogy, III, Ped...",Worcester United States
33816,33816,United States,Clark University,301.0,Community Global Health,MHS,English,6.5,"[Academic, Requirements, Create, account, our\...","[Social, determinants, health, health, inequit...",Worcester United States

In [25]:
University_data.drop( University_data.columns[[ 0  ]] , axis = 1  ,  inplace=True)

Here we have to select some key points that  based on unversity and magor .

In [5]:
# here we add a new column with null value
University_data["Keys"] = None

In [25]:
for item in range(len(University_data)) :
    key = ""
    key+= str(University_data.loc[item]["country_name"]) + ","
    key += str (University_data.loc[item]["university_name"]) + ","
    #      if university ranking < 300 we named it "elit University" else we named it "good University"
    if University_data.loc[item]["university_rank"] < 300.0 :
        key += "elit University"+","
    else : 
        key += "good University ,"
    
    key+= str(University_data.loc[item]["program_name"])+','
    key+= str(University_data.loc[item]["program_type"])+','
    
    if University_data.loc[item]["ielts_score"] > 6 :
        key += "Advanced English Requiremnet,"
    else :
        key+= "Intermediate English Requiremnet,"
    
    key+=str(University_data.loc[item]["academic_req"])+','
    key+= str(University_data.loc[item]["city_wo_punct"])+','
    University_data.loc[University_data.index == item , "Keys"] = key